In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
y=np.array([[[1,2,3],[2,3,4]]])
y

array([[[1, 2, 3],
        [2, 3, 4]]])

# dimension

x=np.array([1,2,3,4])
x

In [5]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [6]:
x.ndim

1

In [7]:
type(x)

numpy.ndarray

In [8]:
y=np.array([[1,2,3],[3,4,5]])
y

array([[1, 2, 3],
       [3, 4, 5]])

In [9]:
y.ndim

2

In [10]:
x.size

4

In [11]:
y.size

6

In [12]:
y.shape

(2, 3)

In [13]:
y

array([[1, 2, 3],
       [3, 4, 5]])

In [14]:
x.shape

(4,)

In [15]:
x.dtype

dtype('int32')

In [16]:
y.dtype

dtype('int32')

# ones matrix

In [17]:
z=np.ones((3,3))
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
z.dtype

dtype('float64')

In [19]:
z=np.ones((3,3),dtype=int)
z


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# zero;s

In [20]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
z.dtype

dtype('float64')

In [22]:
z=np.zeros((3,3),dtype=int)
z


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# arange()

In [23]:
one_D=np.arange(1,10)
one_D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
one_D.ndim

1

# linspace()

In [25]:
y=np.linspace(2,9,5)
y

array([2.  , 3.75, 5.5 , 7.25, 9.  ])

# 1D TO Multidim array

In [26]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
y=np.arange(1,10)#id array
y.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# multidim to 1D

In [28]:
#ravel()      flatten()
x=np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
x.ndim

2

In [57]:
y=x.ravel()
y


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
y.ndim

1

In [31]:
x=np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
x.flatten()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [33]:
y.ndim

1

# Transpose-----row--col     col--row

In [34]:
z=np.arange(1,17).reshape(4,4)
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
z.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

# mathematical function

In [36]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
x+y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [39]:
np.add(x,y)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [40]:
#subtract
x-y

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [41]:
np.subtract(x,y)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
x/y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.divide(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
x*y

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [45]:
np.multiply(x,y)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [46]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#matrix multiplicatio
x@y

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [49]:
x.dot(y)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# max()    min()

In [50]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
x.max()

9

In [52]:
x.argmax()

8